### ISSUE TITLE
pypi name

### ISSUE THREAD

**Issue by nsheff** [daniyall/pyPiper#5]
Hi @daniyall,
I just came across your pyPiper package and have a request for you... is there any way you'd be willing to let me use the pypi namespace for "pypiper"? I've been working for several years now on a project, which I also called "pypiper", which you can see at these links:

https://github.com/databio/pypiper

http://pypiper.readthedocs.io/

I finally got around to trying to submit it to pypi and realized you just reserved the name in the python package index. Since your project is relatively new, is there any chance I can get you to let me use it?

**Comment by daniyall** [comment]
Hi @nsheff,
I'm sorry about the name confict, but this is a project I plan to continue working on and would prefer to keep the name.

**Comment by nsheff** [comment]
Ok, thanks anyway. By the way, I sent you an e-mail (to your outlook address) with a bit more of my rationale, did you have a chance to read that? I feel like a bit of an idiot because when I started this project more than 3 years ago I made sure the name was available...but then I didn't try to register it in pypi until this year, and I was about 3 weeks after you had already registered it. Oh well, I guess, finders keepers, right?

**Comment by nsheff** [comment]
Hi @daniyall -- please let me know if there's anything I can do that would convince you to reconsider. After thinking about it more, unfortunately I think I'm too far along to change the name of my project (too many dependencies, materials, people using it) so I'll end up needing to register something like `pypiper2` on pypi, which is going to lead to some confusion for people for both of our packages in the future... your users may think `pypiper2` is a new version of your package, and so on... but really they're completely different things. we have a chance to solve it right now, and I think it makes more sense if you'd be willing to change names since your package is earlier stage -- but I know it's not ideal for you, and I would greatly appreciate it, and would be happy to do whatever I can to contribute if that helps. But anyway, let me know if you'd be willing to reconsider. thanks.

**Comment by daniyall** [comment]
If registering as pypiper2 works for you then how about databio-pypiper instead? That would avoid the confusion and be just as easy to do.

**Comment by nsheff** [comment]
hmm -- databio is my lab organization name. that doesn't really work though because pypiper has authors not in my lab, so I can't really brand it that way. And it is independent of data and bio (useful beyond biology, for example), so it would be kind of a misnomer, and it's quite long.

**Comment by nsheff** [comment]
Hi @daniyall just wanted to check in one last time and see if you'd be willing to reconsider. I've noticed you haven't really continued development on this project over the past few months so I thought you might be willing to relinquish the name after all. I'm planning to release some software soon that depends on my `pypiper` software and would love to use the name if you'd be willing! Thanks again for your consideration.

**Comment by nsheff** [comment]
Hi @daniyall,

Just wanted to follow-up on this and ask again now that it's 18 months later. are you still planning to continue this project? If not would you consider allowing us to use the pypi name now? 

The reason I bring it up is that we're having a name conflict with conda packaging -- before you registered pypi/pypiper we had a conda/pypiper package, and this is causing us [a naming conflict](https://github.com/bioconda/bioconda-recipes/pull/16372#issuecomment-529006306) since now it doesn't match the pypi name. So if you're not actively developing pypiper please let me know! I can also give you the pypi name [piper](https://pypi.org/project/piper/), which is what we have been using, if that helps.

**Comment by daniyall** [comment]
Hi @nsheff,

PyPiper is the basis for many different projects, some open source (e.g. https://github.com/SPOClab-ca/COVFEFE) and some used internally. So while there haven't been changes to PyPiper for a while, it is being used and changing the name is just as inconvenient for us as it is for you.

**Comment by nsheff** [comment]
Alright, thanks anyway.

**Comment by nsheff** [comment]
Hi @daniyall -- just wanted to follow up. It seems that this project hasn't been updated in 4+ years so I thought you might reconsider. Perhaps now several years later you'd be willing to let me use the pypiper name on pypi yet? Thanks!
