### ISSUE TITLE
in_streams vs in_name in Node constructor

### ISSUE THREAD

**Issue by mmEissen** [daniyall/pyPiper#9]
The init method of the Node accepts the `in_streams` argument, which suggests that a node can accept more than one input stream. This param is however documented as `in_name`, suggesting that only one input stream is possible.

To me it is unclear whether I can define only one input stream or more than one.

If multiple input streams are in fact possible, it would be great to add an example demonstrating this to the README.md

**Comment by daniyall** [comment]
Thanks for pointing this out. Yes, multiple input streams are possible. I will update the doc string and readme by sometime next week.

**Comment by daniyall** [comment]
Fixed in 14b35a09e611d7a0d004ad629778a526148e1197

Thanks again for your feedback.
